# Generated by Django 2.2.1 on 2019-12-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_user_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_create_date',
        ),
    ]
